// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: example.proto

package example

import (
	fmt "fmt"
	_ "github.com/bifrostcloud/protoc-gen-httpclient/proto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type FooRequest struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	SomeOther            string   `protobuf:"bytes,3,opt,name=some_other,json=someOther,proto3" json:"some_other,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FooRequest) Reset()         { *m = FooRequest{} }
func (m *FooRequest) String() string { return proto.CompactTextString(m) }
func (*FooRequest) ProtoMessage()    {}
func (*FooRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{0}
}
func (m *FooRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FooRequest.Unmarshal(m, b)
}
func (m *FooRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FooRequest.Marshal(b, m, deterministic)
}
func (m *FooRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FooRequest.Merge(m, src)
}
func (m *FooRequest) XXX_Size() int {
	return xxx_messageInfo_FooRequest.Size(m)
}
func (m *FooRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FooRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FooRequest proto.InternalMessageInfo

func (m *FooRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *FooRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *FooRequest) GetSomeOther() string {
	if m != nil {
		return m.SomeOther
	}
	return ""
}

type FooResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FooResponse) Reset()         { *m = FooResponse{} }
func (m *FooResponse) String() string { return proto.CompactTextString(m) }
func (*FooResponse) ProtoMessage()    {}
func (*FooResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{1}
}
func (m *FooResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FooResponse.Unmarshal(m, b)
}
func (m *FooResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FooResponse.Marshal(b, m, deterministic)
}
func (m *FooResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FooResponse.Merge(m, src)
}
func (m *FooResponse) XXX_Size() int {
	return xxx_messageInfo_FooResponse.Size(m)
}
func (m *FooResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FooResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FooResponse proto.InternalMessageInfo

func (m *FooResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *FooResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type BarRequest struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Boolean              bool     `protobuf:"varint,2,opt,name=boolean,proto3" json:"boolean,omitempty"`
	Integer              uint32   `protobuf:"varint,3,opt,name=integer,proto3" json:"integer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BarRequest) Reset()         { *m = BarRequest{} }
func (m *BarRequest) String() string { return proto.CompactTextString(m) }
func (*BarRequest) ProtoMessage()    {}
func (*BarRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{2}
}
func (m *BarRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BarRequest.Unmarshal(m, b)
}
func (m *BarRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BarRequest.Marshal(b, m, deterministic)
}
func (m *BarRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BarRequest.Merge(m, src)
}
func (m *BarRequest) XXX_Size() int {
	return xxx_messageInfo_BarRequest.Size(m)
}
func (m *BarRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BarRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BarRequest proto.InternalMessageInfo

func (m *BarRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *BarRequest) GetBoolean() bool {
	if m != nil {
		return m.Boolean
	}
	return false
}

func (m *BarRequest) GetInteger() uint32 {
	if m != nil {
		return m.Integer
	}
	return 0
}

type BarResponse struct {
	Response             string   `protobuf:"bytes,3,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BarResponse) Reset()         { *m = BarResponse{} }
func (m *BarResponse) String() string { return proto.CompactTextString(m) }
func (*BarResponse) ProtoMessage()    {}
func (*BarResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{3}
}
func (m *BarResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BarResponse.Unmarshal(m, b)
}
func (m *BarResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BarResponse.Marshal(b, m, deterministic)
}
func (m *BarResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BarResponse.Merge(m, src)
}
func (m *BarResponse) XXX_Size() int {
	return xxx_messageInfo_BarResponse.Size(m)
}
func (m *BarResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BarResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BarResponse proto.InternalMessageInfo

func (m *BarResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

type BazRequest struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Boolean              bool     `protobuf:"varint,2,opt,name=boolean,proto3" json:"boolean,omitempty"`
	Integer              uint32   `protobuf:"varint,3,opt,name=integer,proto3" json:"integer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BazRequest) Reset()         { *m = BazRequest{} }
func (m *BazRequest) String() string { return proto.CompactTextString(m) }
func (*BazRequest) ProtoMessage()    {}
func (*BazRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{4}
}
func (m *BazRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BazRequest.Unmarshal(m, b)
}
func (m *BazRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BazRequest.Marshal(b, m, deterministic)
}
func (m *BazRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BazRequest.Merge(m, src)
}
func (m *BazRequest) XXX_Size() int {
	return xxx_messageInfo_BazRequest.Size(m)
}
func (m *BazRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BazRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BazRequest proto.InternalMessageInfo

func (m *BazRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *BazRequest) GetBoolean() bool {
	if m != nil {
		return m.Boolean
	}
	return false
}

func (m *BazRequest) GetInteger() uint32 {
	if m != nil {
		return m.Integer
	}
	return 0
}

type BazResponse struct {
	Response             string   `protobuf:"bytes,3,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BazResponse) Reset()         { *m = BazResponse{} }
func (m *BazResponse) String() string { return proto.CompactTextString(m) }
func (*BazResponse) ProtoMessage()    {}
func (*BazResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{5}
}
func (m *BazResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BazResponse.Unmarshal(m, b)
}
func (m *BazResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BazResponse.Marshal(b, m, deterministic)
}
func (m *BazResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BazResponse.Merge(m, src)
}
func (m *BazResponse) XXX_Size() int {
	return xxx_messageInfo_BazResponse.Size(m)
}
func (m *BazResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BazResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BazResponse proto.InternalMessageInfo

func (m *BazResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

func init() {
	proto.RegisterType((*FooRequest)(nil), "example.FooRequest")
	proto.RegisterType((*FooResponse)(nil), "example.FooResponse")
	proto.RegisterType((*BarRequest)(nil), "example.BarRequest")
	proto.RegisterType((*BarResponse)(nil), "example.BarResponse")
	proto.RegisterType((*BazRequest)(nil), "example.BazRequest")
	proto.RegisterType((*BazResponse)(nil), "example.BazResponse")
}

func init() { proto.RegisterFile("example.proto", fileDescriptor_15a1dc8d40dadaa6) }

var fileDescriptor_15a1dc8d40dadaa6 = []byte{
	// 412 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x92, 0xcd, 0x6a, 0xd5, 0x40,
	0x14, 0xc7, 0xb9, 0xcd, 0xb5, 0xbd, 0x3d, 0xa5, 0x0a, 0xe3, 0x57, 0x08, 0xf8, 0xc1, 0x28, 0x52,
	0x91, 0xdc, 0x14, 0xdd, 0x94, 0x6e, 0x8a, 0x05, 0x0b, 0x2e, 0x44, 0x88, 0x20, 0x6e, 0x8a, 0x4c,
	0xc6, 0xd3, 0x64, 0x30, 0xc9, 0x89, 0x33, 0x27, 0x62, 0xf3, 0x3a, 0x7d, 0x08, 0x5f, 0xa9, 0xf8,
	0x08, 0xae, 0x24, 0x5f, 0x6d, 0x2e, 0xb8, 0xb8, 0x2e, 0xdc, 0xe5, 0xff, 0x3f, 0x99, 0x1f, 0xff,
	0xf3, 0x01, 0xbb, 0xf8, 0x43, 0x15, 0x55, 0x8e, 0xcb, 0xca, 0x12, 0x93, 0xd8, 0x1a, 0x64, 0x70,
	0x94, 0x1a, 0xce, 0xea, 0x64, 0xa9, 0xa9, 0x88, 0x12, 0x73, 0x66, 0xc9, 0xb1, 0xce, 0xa9, 0xfe,
	0x12, 0x75, 0xff, 0xe9, 0x30, 0xc5, 0x32, 0xcc, 0x98, 0x2b, 0x9d, 0x1b, 0x2c, 0xb9, 0x77, 0x23,
	0x3e, 0xaf, 0xd0, 0xf5, 0x24, 0x79, 0x0a, 0x70, 0x42, 0x14, 0xe3, 0xb7, 0x1a, 0x1d, 0x8b, 0x7b,
	0xb0, 0xe9, 0x58, 0x71, 0xed, 0xfc, 0xd9, 0xe3, 0xd9, 0xde, 0x76, 0x3c, 0x28, 0xe1, 0xc3, 0x56,
	0x81, 0xce, 0xa9, 0x14, 0xfd, 0x8d, 0xae, 0x30, 0x4a, 0xf1, 0x00, 0xc0, 0x51, 0x81, 0x9f, 0x89,
	0x33, 0xb4, 0xbe, 0xd7, 0x15, 0xb7, 0x5b, 0xe7, 0x7d, 0x6b, 0xc8, 0x23, 0xd8, 0xe9, 0xf0, 0xae,
	0xa2, 0xd2, 0xe1, 0xbf, 0xf3, 0xe5, 0x27, 0x80, 0x63, 0x65, 0xd7, 0xc8, 0x97, 0x10, 0xe5, 0xa8,
	0xca, 0xee, 0xfd, 0x22, 0x1e, 0x65, 0x5b, 0x31, 0x25, 0x63, 0x3a, 0x84, 0xdb, 0x8d, 0x47, 0x29,
	0x9f, 0xc3, 0x4e, 0x47, 0x1e, 0xa2, 0x05, 0xb0, 0xb0, 0xc3, 0xf7, 0xd0, 0xc6, 0x95, 0xee, 0x43,
	0x34, 0xff, 0x2d, 0x44, 0xb3, 0x4e, 0x88, 0x97, 0x3f, 0x37, 0xe0, 0xe6, 0x9b, 0x7e, 0xed, 0x1f,
	0xd0, 0x7e, 0x37, 0x1a, 0xc5, 0x29, 0x78, 0x27, 0x44, 0xe2, 0xf6, 0x72, 0xbc, 0x8e, 0xeb, 0x55,
	0x06, 0x77, 0x56, 0xcd, 0xa1, 0x93, 0x17, 0xbf, 0x2e, 0x2e, 0xbd, 0x67, 0x70, 0x4b, 0x1b, 0xab,
	0x6b, 0xc3, 0x61, 0x62, 0x51, 0x7d, 0x45, 0x2b, 0xe6, 0xd1, 0x19, 0x51, 0xb0, 0x78, 0x77, 0x1e,
	0xbe, 0x4e, 0xb1, 0x64, 0xe9, 0xa5, 0xc8, 0xe2, 0x2d, 0x78, 0xc7, 0xca, 0x4e, 0xf0, 0xd7, 0x9b,
	0x98, 0xe0, 0x27, 0x43, 0x94, 0xf7, 0x5b, 0xbc, 0x80, 0x1b, 0x89, 0x72, 0x46, 0x8b, 0x79, 0x94,
	0x28, 0x2b, 0xbd, 0xaa, 0x66, 0xf1, 0xb1, 0x45, 0x35, 0x2b, 0xa8, 0xe6, 0x6f, 0xa8, 0xab, 0x51,
	0xc8, 0xa7, 0x2d, 0xea, 0xd1, 0x14, 0xd5, 0x4c, 0xf2, 0xcd, 0x2b, 0x72, 0xbc, 0x37, 0x0b, 0x9e,
	0xfc, 0xbe, 0xb8, 0xf4, 0x1e, 0xc2, 0xdd, 0xf6, 0xc6, 0x0f, 0xa3, 0x28, 0x27, 0xad, 0xf2, 0x8c,
	0x1c, 0x1f, 0x1e, 0xec, 0x1f, 0xec, 0x8b, 0xfe, 0x71, 0xb2, 0xd9, 0x9d, 0xfa, 0xab, 0x3f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x5c, 0xd9, 0xe8, 0x7b, 0x45, 0x03, 0x00, 0x00,
}
