// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestOptions struct {
	ClientType           string   `protobuf:"bytes,1,opt,name=client_type,json=clientType,proto3" json:"client_type,omitempty"`
	Target               string   `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Useragent            string   `protobuf:"bytes,3,opt,name=useragent,proto3" json:"useragent,omitempty"`
	Method               string   `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	Param                bool     `protobuf:"varint,5,opt,name=param,proto3" json:"param,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestOptions) Reset()         { *m = RequestOptions{} }
func (m *RequestOptions) String() string { return proto.CompactTextString(m) }
func (*RequestOptions) ProtoMessage()    {}
func (*RequestOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

func (m *RequestOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestOptions.Unmarshal(m, b)
}
func (m *RequestOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestOptions.Marshal(b, m, deterministic)
}
func (m *RequestOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestOptions.Merge(m, src)
}
func (m *RequestOptions) XXX_Size() int {
	return xxx_messageInfo_RequestOptions.Size(m)
}
func (m *RequestOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestOptions.DiscardUnknown(m)
}

var xxx_messageInfo_RequestOptions proto.InternalMessageInfo

func (m *RequestOptions) GetClientType() string {
	if m != nil {
		return m.ClientType
	}
	return ""
}

func (m *RequestOptions) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *RequestOptions) GetUseragent() string {
	if m != nil {
		return m.Useragent
	}
	return ""
}

func (m *RequestOptions) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *RequestOptions) GetParam() bool {
	if m != nil {
		return m.Param
	}
	return false
}

type ServiceOptions struct {
	Endpoint             string   `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Auth                 string   `protobuf:"bytes,2,opt,name=auth,proto3" json:"auth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceOptions) Reset()         { *m = ServiceOptions{} }
func (m *ServiceOptions) String() string { return proto.CompactTextString(m) }
func (*ServiceOptions) ProtoMessage()    {}
func (*ServiceOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{1}
}

func (m *ServiceOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceOptions.Unmarshal(m, b)
}
func (m *ServiceOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceOptions.Marshal(b, m, deterministic)
}
func (m *ServiceOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceOptions.Merge(m, src)
}
func (m *ServiceOptions) XXX_Size() int {
	return xxx_messageInfo_ServiceOptions.Size(m)
}
func (m *ServiceOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceOptions.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceOptions proto.InternalMessageInfo

func (m *ServiceOptions) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *ServiceOptions) GetAuth() string {
	if m != nil {
		return m.Auth
	}
	return ""
}

var E_RequestOptions = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*RequestOptions)(nil),
	Field:         999997,
	Name:          "request_options",
	Tag:           "bytes,999997,opt,name=request_options",
	Filename:      "types.proto",
}

var E_ServiceOptions = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.ServiceOptions)(nil),
	ExtensionType: (*ServiceOptions)(nil),
	Field:         999999,
	Name:          "service_options",
	Tag:           "bytes,999999,opt,name=service_options",
	Filename:      "types.proto",
}

func init() {
	proto.RegisterType((*RequestOptions)(nil), "RequestOptions")
	proto.RegisterType((*ServiceOptions)(nil), "ServiceOptions")
	proto.RegisterExtension(E_RequestOptions)
	proto.RegisterExtension(E_ServiceOptions)
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_d938547f84707355) }

var fileDescriptor_d938547f84707355 = []byte{
	// 288 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0x87, 0x49, 0xdf, 0xb4, 0xb4, 0x13, 0x48, 0x60, 0x79, 0x91, 0xa5, 0x88, 0x0d, 0x3d, 0xe5,
	0x94, 0x82, 0xde, 0x0a, 0x82, 0x78, 0x17, 0x21, 0x7a, 0xaa, 0x87, 0x92, 0x3f, 0x63, 0x1a, 0x68,
	0xb3, 0xeb, 0xee, 0x44, 0xe8, 0xdd, 0xaf, 0xe0, 0xc7, 0x11, 0xbf, 0x9a, 0x74, 0x37, 0x8d, 0x2c,
	0xde, 0xf6, 0x99, 0xd9, 0xf9, 0xed, 0xb3, 0x03, 0x01, 0x1d, 0x25, 0xea, 0x54, 0x2a, 0x41, 0x62,
	0x1e, 0xd7, 0x42, 0xd4, 0x7b, 0x5c, 0x19, 0x2a, 0xba, 0xd7, 0x55, 0x85, 0xba, 0x54, 0x8d, 0x24,
	0xa1, 0xec, 0x8d, 0xe5, 0xa7, 0x07, 0x61, 0x86, 0x6f, 0x1d, 0x6a, 0x7a, 0x94, 0xd4, 0x88, 0x56,
	0xb3, 0x05, 0x04, 0xe5, 0xbe, 0xc1, 0x96, 0xb6, 0xa7, 0x28, 0xee, 0xc5, 0x5e, 0x32, 0xcb, 0xc0,
	0x96, 0x9e, 0x8f, 0x12, 0xd9, 0x05, 0x4c, 0x28, 0x57, 0x35, 0x12, 0x1f, 0x99, 0x5e, 0x4f, 0xec,
	0x12, 0x66, 0x9d, 0x46, 0x95, 0xd7, 0xd8, 0x12, 0xff, 0x67, 0x5a, 0xbf, 0x85, 0xd3, 0xd4, 0x01,
	0x69, 0x27, 0x2a, 0xee, 0xdb, 0x29, 0x4b, 0xec, 0x3f, 0x8c, 0x65, 0xae, 0xf2, 0x03, 0x1f, 0xc7,
	0x5e, 0x32, 0xcd, 0x2c, 0x2c, 0xef, 0x20, 0x7c, 0x42, 0xf5, 0xde, 0x94, 0x78, 0xd6, 0x9a, 0xc3,
	0x14, 0xdb, 0x4a, 0x8a, 0xa6, 0xa5, 0xde, 0x69, 0x60, 0xc6, 0xc0, 0xcf, 0x3b, 0xda, 0xf5, 0x3e,
	0xe6, 0xbc, 0xde, 0x40, 0xa4, 0xec, 0xc7, 0xb6, 0xa2, 0x8f, 0xb8, 0x4a, 0xed, 0x3e, 0xd2, 0xf3,
	0x3e, 0xd2, 0x07, 0xe3, 0xd0, 0x3f, 0xc1, 0xbf, 0x3e, 0x6e, 0x63, 0x2f, 0x09, 0xae, 0xa3, 0xd4,
	0x5d, 0x49, 0x16, 0x2a, 0x87, 0xd7, 0x2f, 0x10, 0x69, 0x6b, 0x37, 0x64, 0x2f, 0xfe, 0x64, 0xbb,
	0xfe, 0xfc, 0x7b, 0x08, 0x77, 0x1b, 0x59, 0xa8, 0x1d, 0xbe, 0xf7, 0x37, 0x23, 0x59, 0x14, 0x13,
	0x93, 0x73, 0xf3, 0x13, 0x00, 0x00, 0xff, 0xff, 0x27, 0xb2, 0xa5, 0x20, 0xd0, 0x01, 0x00, 0x00,
}
